/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * The type of the address.
 */
export enum AccountingCustomer20230207AddressesType {
    Billing = "billing",
    Shipping = "shipping",
    PoBox = "po_box",
    Unknown = "unknown",
}

export class AccountingCustomer20230207Addresses extends SpeakeasyBase {
    /**
     * The first address line of the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "address1" })
    address1: string;

    /**
     * The second address line of the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "address2" })
    address2: string;

    /**
     * The city of the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "city" })
    city: string;

    /**
     * The country of the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "country" })
    country: string;

    /**
     * The postal code of the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "postal_code" })
    postalCode: string;

    /**
     * The region or state of the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "region" })
    region: string;

    /**
     * The type of the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type: AccountingCustomer20230207AddressesType;
}

export enum AccountingCustomer20230207Status {
    Active = "ACTIVE",
    Inactive = "INACTIVE",
    Unknown = "UNKNOWN",
}

export class AccountingCustomer20230207 extends SpeakeasyBase {
    /**
     * An array of addresses linked to the customer.
     */
    @SpeakeasyMetadata({ elemType: AccountingCustomer20230207Addresses })
    @Expose({ name: "addresses" })
    @Type(() => AccountingCustomer20230207Addresses)
    addresses: AccountingCustomer20230207Addresses[];

    /**
     * The name of the primary contact of the customer.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "contact_name" })
    contactName: string;

    /**
     * The [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html) currency code of the customer.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "currency_code" })
    currencyCode: string;

    /**
     * The business name of the customer.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "customer_name" })
    customerName: string;

    /**
     * The email of the customer.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "email" })
    email: string;

    /**
     * The Rutter generated unique ID of the customer.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    /**
     * The phone number of the customer.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "phone" })
    phone: string;

    /**
     * The raw platform data corresponding to the Rutter object.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "platform_data" })
    platformData?: Record<string, any>;

    /**
     * The platform specific ID of the customer.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "platform_id" })
    platformId: string;

    /**
     * The registration number of the customer
     */
    @SpeakeasyMetadata()
    @Expose({ name: "registration_number" })
    registrationNumber: string;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status: AccountingCustomer20230207Status;

    /**
     * The Rutter ID of the [Subsidiary](/rest/version/subsidiaries) linked to the customer. This feature is currently only supported on NetSuite.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "subsidiary_id" })
    subsidiaryId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "tax_number" })
    taxNumber: string;

    @SpeakeasyMetadata()
    @Expose({ name: "updated_at" })
    updatedAt: string;
}
