/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AccountingCustomer20230207 } from "./accountingcustomer20230207";
import { Expose, Type } from "class-transformer";

export class AccountingCustomer20230207Response extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "customer" })
    @Type(() => AccountingCustomer20230207)
    customer: AccountingCustomer20230207;
}
