/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AggregateMetric } from "./aggregatemetric";
import { Connection } from "./connection";
import { Expose, Type } from "class-transformer";

export class AggregateMetricResponse extends SpeakeasyBase {
    /**
     * The metric value and important metadata that defines the method of calculation.
     */
    @SpeakeasyMetadata({ elemType: AggregateMetric })
    @Expose({ name: "active_customers" })
    @Type(() => AggregateMetric)
    activeCustomers?: AggregateMetric[];

    /**
     * The metric value and important metadata that defines the method of calculation.
     */
    @SpeakeasyMetadata({ elemType: AggregateMetric })
    @Expose({ name: "amortization_expense" })
    @Type(() => AggregateMetric)
    amortizationExpense?: AggregateMetric[];

    /**
     * The metric value and important metadata that defines the method of calculation.
     */
    @SpeakeasyMetadata({ elemType: AggregateMetric })
    @Expose({ name: "capital_expenditure" })
    @Type(() => AggregateMetric)
    capitalExpenditure?: AggregateMetric[];

    /**
     * The metric value and important metadata that defines the method of calculation.
     */
    @SpeakeasyMetadata({ elemType: AggregateMetric })
    @Expose({ name: "change_in_working_capital" })
    @Type(() => AggregateMetric)
    changeInWorkingCapital?: AggregateMetric[];

    /**
     * The [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) timestamp for the date at which the metric was last updated.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "checkpoint" })
    checkpoint: string;

    @SpeakeasyMetadata()
    @Expose({ name: "connection" })
    @Type(() => Connection)
    connection: Connection;

    /**
     * The metric value and important metadata that defines the method of calculation.
     */
    @SpeakeasyMetadata({ elemType: AggregateMetric })
    @Expose({ name: "cost_of_goods_sold" })
    @Type(() => AggregateMetric)
    costOfGoodsSold?: AggregateMetric[];

    /**
     * The metric value and important metadata that defines the method of calculation.
     */
    @SpeakeasyMetadata({ elemType: AggregateMetric })
    @Expose({ name: "current_assets" })
    @Type(() => AggregateMetric)
    currentAssets?: AggregateMetric[];

    /**
     * The metric value and important metadata that defines the method of calculation.
     */
    @SpeakeasyMetadata({ elemType: AggregateMetric })
    @Expose({ name: "current_liabilities" })
    @Type(() => AggregateMetric)
    currentLiabilities?: AggregateMetric[];

    /**
     * The metric value and important metadata that defines the method of calculation.
     */
    @SpeakeasyMetadata({ elemType: AggregateMetric })
    @Expose({ name: "current_ratio" })
    @Type(() => AggregateMetric)
    currentRatio?: AggregateMetric[];

    /**
     * The metric value and important metadata that defines the method of calculation.
     */
    @SpeakeasyMetadata({ elemType: AggregateMetric })
    @Expose({ name: "debt_service" })
    @Type(() => AggregateMetric)
    debtService?: AggregateMetric[];

    /**
     * The metric value and important metadata that defines the method of calculation.
     */
    @SpeakeasyMetadata({ elemType: AggregateMetric })
    @Expose({ name: "debt_service_coverage_ratio" })
    @Type(() => AggregateMetric)
    debtServiceCoverageRatio?: AggregateMetric[];

    /**
     * The metric value and important metadata that defines the method of calculation.
     */
    @SpeakeasyMetadata({ elemType: AggregateMetric })
    @Expose({ name: "debt_service_from_income_statement" })
    @Type(() => AggregateMetric)
    debtServiceFromIncomeStatement?: AggregateMetric[];

    /**
     * The metric value and important metadata that defines the method of calculation.
     */
    @SpeakeasyMetadata({ elemType: AggregateMetric })
    @Expose({ name: "debt_service_from_principal_paid" })
    @Type(() => AggregateMetric)
    debtServiceFromPrincipalPaid?: AggregateMetric[];

    /**
     * The metric value and important metadata that defines the method of calculation.
     */
    @SpeakeasyMetadata({ elemType: AggregateMetric })
    @Expose({ name: "depreciation_expense" })
    @Type(() => AggregateMetric)
    depreciationExpense?: AggregateMetric[];

    /**
     * The metric value and important metadata that defines the method of calculation.
     */
    @SpeakeasyMetadata({ elemType: AggregateMetric })
    @Expose({ name: "ebitda" })
    @Type(() => AggregateMetric)
    ebitda?: AggregateMetric[];

    /**
     * The metric value and important metadata that defines the method of calculation.
     */
    @SpeakeasyMetadata({ elemType: AggregateMetric })
    @Expose({ name: "ebitda_margin" })
    @Type(() => AggregateMetric)
    ebitdaMargin?: AggregateMetric[];

    /**
     * The metric value and important metadata that defines the method of calculation.
     */
    @SpeakeasyMetadata({ elemType: AggregateMetric })
    @Expose({ name: "enterprise_free_cash_flow" })
    @Type(() => AggregateMetric)
    enterpriseFreeCashFlow?: AggregateMetric[];

    /**
     * The metric value and important metadata that defines the method of calculation.
     */
    @SpeakeasyMetadata({ elemType: AggregateMetric })
    @Expose({ name: "enterprise_free_cash_flow_formula_two" })
    @Type(() => AggregateMetric)
    enterpriseFreeCashFlowFormulaTwo?: AggregateMetric[];

    /**
     * The metric value and important metadata that defines the method of calculation.
     */
    @SpeakeasyMetadata({ elemType: AggregateMetric })
    @Expose({ name: "gross_profit_margin" })
    @Type(() => AggregateMetric)
    grossProfitMargin?: AggregateMetric[];

    /**
     * The metric value and important metadata that defines the method of calculation.
     */
    @SpeakeasyMetadata({ elemType: AggregateMetric })
    @Expose({ name: "interest_expense" })
    @Type(() => AggregateMetric)
    interestExpense?: AggregateMetric[];

    /**
     * The metric value and important metadata that defines the method of calculation.
     */
    @SpeakeasyMetadata({ elemType: AggregateMetric })
    @Expose({ name: "inventory" })
    @Type(() => AggregateMetric)
    inventory?: AggregateMetric[];

    /**
     * The metric value and important metadata that defines the method of calculation.
     */
    @SpeakeasyMetadata({ elemType: AggregateMetric })
    @Expose({ name: "net_income" })
    @Type(() => AggregateMetric)
    netIncome?: AggregateMetric[];

    /**
     * The metric value and important metadata that defines the method of calculation.
     */
    @SpeakeasyMetadata({ elemType: AggregateMetric })
    @Expose({ name: "net_operating_income" })
    @Type(() => AggregateMetric)
    netOperatingIncome?: AggregateMetric[];

    /**
     * The metric value and important metadata that defines the method of calculation.
     */
    @SpeakeasyMetadata({ elemType: AggregateMetric })
    @Expose({ name: "prepaid_expenses" })
    @Type(() => AggregateMetric)
    prepaidExpenses?: AggregateMetric[];

    /**
     * The metric value and important metadata that defines the method of calculation.
     */
    @SpeakeasyMetadata({ elemType: AggregateMetric })
    @Expose({ name: "principal_paid" })
    @Type(() => AggregateMetric)
    principalPaid?: AggregateMetric[];

    /**
     * The metric value and important metadata that defines the method of calculation.
     */
    @SpeakeasyMetadata({ elemType: AggregateMetric })
    @Expose({ name: "quick_ratio" })
    @Type(() => AggregateMetric)
    quickRatio?: AggregateMetric[];

    /**
     * The metric value and important metadata that defines the method of calculation.
     */
    @SpeakeasyMetadata({ elemType: AggregateMetric })
    @Expose({ name: "refund_rate" })
    @Type(() => AggregateMetric)
    refundRate?: AggregateMetric[];

    /**
     * The metric value and important metadata that defines the method of calculation.
     */
    @SpeakeasyMetadata({ elemType: AggregateMetric })
    @Expose({ name: "rental_expense" })
    @Type(() => AggregateMetric)
    rentalExpense?: AggregateMetric[];

    /**
     * The metric value and important metadata that defines the method of calculation.
     */
    @SpeakeasyMetadata({ elemType: AggregateMetric })
    @Expose({ name: "total_expenses" })
    @Type(() => AggregateMetric)
    totalExpenses?: AggregateMetric[];

    /**
     * The metric value and important metadata that defines the method of calculation.
     */
    @SpeakeasyMetadata({ elemType: AggregateMetric })
    @Expose({ name: "total_income" })
    @Type(() => AggregateMetric)
    totalIncome?: AggregateMetric[];

    /**
     * The metric value and important metadata that defines the method of calculation.
     */
    @SpeakeasyMetadata({ elemType: AggregateMetric })
    @Expose({ name: "total_orders" })
    @Type(() => AggregateMetric)
    totalOrders?: AggregateMetric[];

    /**
     * The metric value and important metadata that defines the method of calculation.
     */
    @SpeakeasyMetadata({ elemType: AggregateMetric })
    @Expose({ name: "total_revenue" })
    @Type(() => AggregateMetric)
    totalRevenue?: AggregateMetric[];

    /**
     * The metric value and important metadata that defines the method of calculation.
     */
    @SpeakeasyMetadata({ elemType: AggregateMetric })
    @Expose({ name: "unearned_revenues" })
    @Type(() => AggregateMetric)
    unearnedRevenues?: AggregateMetric[];

    /**
     * The metric value and important metadata that defines the method of calculation.
     */
    @SpeakeasyMetadata({ elemType: AggregateMetric })
    @Expose({ name: "working_capital" })
    @Type(() => AggregateMetric)
    workingCapital?: AggregateMetric[];
}
