/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class Attachment extends SpeakeasyBase {
    /**
     * The Rutter ID of the entity linked to the attachment.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "attached_to_id" })
    attachedToId: string;

    /**
     * The type of entity linked to the attachment.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "attached_to_type" })
    attachedToType: string;

    /**
     * The [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) timestamp that the attachment was created.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "created_at" })
    createdAt: string;

    /**
     * The file name of the attachment.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "file_name" })
    fileName: string;

    /**
     * The Rutter generated URL containing a downloadable version of the attachment.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "file_url" })
    fileUrl: string;

    /**
     * The Rutter generated unique ID of the attachment.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    /**
     * The platform specific ID of the attachment.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "platform_id" })
    platformId: string;
}
