/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { GeneralLedgerLineItem } from "./generalledgerlineitem";
import { Expose, Type } from "class-transformer";

export class BalanceSheet extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "assets" })
    @Type(() => GeneralLedgerLineItem)
    assets: GeneralLedgerLineItem;

    /**
     * The [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) timestamp that the balance sheet was created.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "created_at" })
    createdAt: string;

    /**
     * The [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html) currency code of the balance sheet.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "currency_code" })
    currencyCode: string;

    /**
     * The [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) timestamp for the end date of the balance sheet.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "end_date" })
    endDate: string;

    @SpeakeasyMetadata()
    @Expose({ name: "equity" })
    @Type(() => GeneralLedgerLineItem)
    equity: GeneralLedgerLineItem;

    /**
     * The Rutter generated unique ID of the balance sheet.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    @SpeakeasyMetadata()
    @Expose({ name: "liabilities" })
    @Type(() => GeneralLedgerLineItem)
    liabilities: GeneralLedgerLineItem;

    /**
     * The raw platform data corresponding to the Rutter object.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "platform_data" })
    platformData?: Record<string, any>;

    /**
     * The [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) timestamp for the start date of the balance sheet.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "start_date" })
    startDate: string;

    /**
     * The total value of Assets.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "total_assets" })
    totalAssets: string;

    /**
     * The total value of Equity.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "total_equity" })
    totalEquity: string;

    /**
     * The total value of Liabilities.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "total_liabilities" })
    totalLiabilities: string;

    /**
     * The [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) timestamp that the balance sheet was last updated.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "updated_at" })
    updatedAt: string;
}
