/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { BillCreditMemo } from "./billcreditmemo";
import { Connection } from "./connection";
import { Expose, Type } from "class-transformer";

export class BillCreditMemoResponseWithConnection extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "bill_credit_memo" })
    @Type(() => BillCreditMemo)
    billCreditMemo: BillCreditMemo;

    @SpeakeasyMetadata()
    @Expose({ name: "connection" })
    @Type(() => Connection)
    connection: Connection;
}
