/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { BillPayment } from "./billpayment";
import { Expose, Type } from "class-transformer";

export class BillPaymentResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "bill_payment" })
    @Type(() => BillPayment)
    billPayment: BillPayment;
}
