/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Bill } from "./bill";
import { Expose, Type } from "class-transformer";

export class BillResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "bill" })
    @Type(() => Bill)
    bill: Bill;
}
