/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { BillPayment } from "./billpayment";
import { Connection } from "./connection";
import { Expose, Type } from "class-transformer";

export class BillPaymentResponseWithConnection extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "bill_payment" })
    @Type(() => BillPayment)
    billPayment: BillPayment;

    @SpeakeasyMetadata()
    @Expose({ name: "connection" })
    @Type(() => Connection)
    connection: Connection;
}
