/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { GeneralLedgerLineItem } from "./generalledgerlineitem";
import { Expose, Type } from "class-transformer";

export class CashFlowStatement extends SpeakeasyBase {
    /**
     * The [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) timestamp that the cash flow statement was created.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "created_at" })
    createdAt: string;

    /**
     * The [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html) currency code of the cash flow statement.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "currency_code" })
    currencyCode: string;

    /**
     * The [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) timestamp for the end date of the cash flow statement.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "end_date" })
    endDate: string;

    /**
     * The amount of cash and cash equivalents at the end of the given period.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "ending_balance" })
    endingBalance: string;

    @SpeakeasyMetadata()
    @Expose({ name: "financing_activities" })
    @Type(() => GeneralLedgerLineItem)
    financingActivities: GeneralLedgerLineItem;

    @SpeakeasyMetadata()
    @Expose({ name: "gross_cash_in_flow" })
    grossCashInFlow?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "gross_cash_out_flow" })
    grossCashOutFlow?: string;

    /**
     * The Rutter generated unique ID of the cash flow statement.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    @SpeakeasyMetadata()
    @Expose({ name: "investing_activities" })
    @Type(() => GeneralLedgerLineItem)
    investingActivities: GeneralLedgerLineItem;

    @SpeakeasyMetadata()
    @Expose({ name: "operating_activities" })
    @Type(() => GeneralLedgerLineItem)
    operatingActivities: GeneralLedgerLineItem;

    /**
     * The raw platform data corresponding to the Rutter object.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "platform_data" })
    platformData?: Record<string, any>;

    /**
     * The [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) timestamp for the start date of the cash flow statement.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "start_date" })
    startDate: string;

    /**
     * The amount of cash and cash equivalents at the start of the given period.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "starting_balance" })
    startingBalance: string;

    /**
     * The total amount of Financing Activities.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "total_financing" })
    totalFinancing: string;

    /**
     * The total amount of Investing Activities.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "total_investing" })
    totalInvesting: string;

    /**
     * The total amount of Operating Activities.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "total_operating" })
    totalOperating: string;

    /**
     * The [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) timestamp that the cash flow statement was last updated.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "updated_at" })
    updatedAt: string;
}
