/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CompanyInfo20230314 } from "./companyinfo20230314";
import { Connection } from "./connection";
import { Expose, Type } from "class-transformer";

export class CompanyInfo20230314ResponseWithConnection extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "company_info" })
    @Type(() => CompanyInfo20230314)
    companyInfo: CompanyInfo20230314;

    @SpeakeasyMetadata()
    @Expose({ name: "connection" })
    @Type(() => Connection)
    connection: Connection;
}
