/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Platform } from "./platform";
import { Expose } from "class-transformer";

export class Connection extends SpeakeasyBase {
    /**
     * The UUID of the connection. Generated by Rutter.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    /**
     * Your organization id.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "orgId" })
    orgId: string;

    /**
     * The underlying platform.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "platform" })
    platform: Platform;
}
