/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CreatePurchaseOrder } from "./createpurchaseorder";
import { Expose, Type } from "class-transformer";

export class CreateCreatePurchaseOrderRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "purchase_order" })
    @Type(() => CreatePurchaseOrder)
    purchaseOrder: CreatePurchaseOrder;
}
