/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CreateBillCreditApplication } from "./createbillcreditapplication";
import { Expose, Type } from "class-transformer";

export class CreateCreateBillCreditApplicationRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "bill_credit_application" })
    @Type(() => CreateBillCreditApplication)
    billCreditApplication: CreateBillCreditApplication;
}
