/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * The accounting item of the line item
 */
export class CreateInvoiceCreditMemoLineItemsItem extends SpeakeasyBase {
    /**
     * The Rutter ID of the accounting item
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    /**
     * The quantity of the line item
     */
    @SpeakeasyMetadata()
    @Expose({ name: "quantity" })
    quantity: number;

    /**
     * The unit amount of the line item
     */
    @SpeakeasyMetadata()
    @Expose({ name: "unit_amount" })
    unitAmount: string;
}

export class CreateInvoiceCreditMemoLineItems extends SpeakeasyBase {
    /**
     * The credited account for the line item
     */
    @SpeakeasyMetadata()
    @Expose({ name: "account_id" })
    accountId?: string;

    /**
     * The description of the line item
     */
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description: string;

    /**
     * The accounting item of the line item
     */
    @SpeakeasyMetadata()
    @Expose({ name: "item" })
    @Type(() => CreateInvoiceCreditMemoLineItemsItem)
    item: CreateInvoiceCreditMemoLineItemsItem;

    /**
     * The total amount of the line item
     */
    @SpeakeasyMetadata()
    @Expose({ name: "total_amount" })
    totalAmount: string;
}

export class CreateInvoiceCreditMemo extends SpeakeasyBase {
    /**
     * The AR account rutter ID
     */
    @SpeakeasyMetadata()
    @Expose({ name: "account_id" })
    accountId: string;

    /**
     * The currency code of the credit memo
     */
    @SpeakeasyMetadata()
    @Expose({ name: "currency_code" })
    currencyCode: string;

    /**
     * The accounting customer ID that is going to get this credit
     */
    @SpeakeasyMetadata()
    @Expose({ name: "customer_id" })
    customerId: string;

    /**
     * Issue date of the credit memo
     */
    @SpeakeasyMetadata()
    @Expose({ name: "issue_date" })
    issueDate: string;

    /**
     * The line items of the credit memo
     */
    @SpeakeasyMetadata({ elemType: CreateInvoiceCreditMemoLineItems })
    @Expose({ name: "line_items" })
    @Type(() => CreateInvoiceCreditMemoLineItems)
    lineItems: CreateInvoiceCreditMemoLineItems[];
}
