/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The underlying platform.
 */
export enum CreateConnectionPlatforms {
    BigCommerce = "BIG_COMMERCE",
    Amazon = "AMAZON",
    Shopify = "SHOPIFY",
    Prestashop = "PRESTASHOP",
    Shoper = "SHOPER",
    WooCommerce = "WOO_COMMERCE",
    Magento = "MAGENTO",
    Ebay = "EBAY",
    Lazada = "LAZADA",
    Fnac = "FNAC",
    Square = "SQUARE",
    Stripe = "STRIPE",
    Quickbooks = "QUICKBOOKS",
    Netsuite = "NETSUITE",
    Walmart = "WALMART",
}
