/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * Additional fields required only for a narrow set of use cases.
 */
export class CreateItemAdditionalFields extends SpeakeasyBase {
    /**
     * (Sage Intacct only) ID of the Item to create.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "item_id" })
    itemId?: string;
}

/**
 * Item details associated with a bill (when the item was purchased).
 */
export class CreateItemBillItem extends SpeakeasyBase {
    /**
     * The default expense account debited to pay the vendor for this bill line item
     */
    @SpeakeasyMetadata()
    @Expose({ name: "account_id" })
    accountId?: string;

    /**
     * The description of the line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    /**
     * The unit price of the line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "unit_price" })
    unitPrice?: string;
}

/**
 * Item details associated with an invoice (when the item was sold).
 */
export class CreateItemInvoiceItem extends SpeakeasyBase {
    /**
     * The default income account credited with the proceeds from the sale of this invoice item
     */
    @SpeakeasyMetadata()
    @Expose({ name: "account_id" })
    accountId?: string;

    /**
     * The description of the line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    /**
     * The unit price of the line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "unit_price" })
    unitPrice?: string;
}

/**
 * The type of the item.
 */
export enum CreateItemType {
    Inventory = "inventory",
    NonInventory = "non_inventory",
    Service = "service",
    Discount = "discount",
    Unknown = "unknown",
}

export class CreateItem extends SpeakeasyBase {
    /**
     * Additional fields required only for a narrow set of use cases.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "additional_fields" })
    @Type(() => CreateItemAdditionalFields)
    additionalFields?: CreateItemAdditionalFields;

    /**
     * Item details associated with a bill (when the item was purchased).
     */
    @SpeakeasyMetadata()
    @Expose({ name: "bill_item" })
    @Type(() => CreateItemBillItem)
    billItem?: CreateItemBillItem;

    /**
     * Item details associated with an invoice (when the item was sold).
     */
    @SpeakeasyMetadata()
    @Expose({ name: "invoice_item" })
    @Type(() => CreateItemInvoiceItem)
    invoiceItem?: CreateItemInvoiceItem;

    /**
     * The name of the item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    /**
     * The type of the item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: CreateItemType;
}
