/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CreateBillPayment } from "./createbillpayment";
import { Expose, Type } from "class-transformer";

export class CreateCreateBillPaymentRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "bill_payment" })
    @Type(() => CreateBillPayment)
    billPayment: CreateBillPayment;
}
