/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * The billing address of the order.
 */
export class CreateOrderBodyOrderBillingAddress extends SpeakeasyBase {
    /**
     * The first address line of the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "address1" })
    address1: string;

    /**
     * An optional second address line of the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "address2" })
    address2: string;

    /**
     * The city, town, or village of the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "city" })
    city: string;

    /**
     * The [ISO 3166-1](https://www.iso.org/iso-3166-country-codes.html) country code for the country of the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "country_code" })
    countryCode: string;

    /**
     * The email for the customer at the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "email" })
    email: string;

    /**
     * The first name of the person associated with the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "first_name" })
    firstName: string;

    /**
     * The last name of the person associated with the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "last_name" })
    lastName: string;

    /**
     * The phone number at the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "phone" })
    phone: string;

    /**
     * The postal code (ZIP, Eircode, etc) of the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "postal_code" })
    postalCode: string;

    /**
     * The abbreviation of the region of the address. For the US, this would be states, for other places, it would be provinces or equivalent.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "region" })
    region: string;
}

/**
 * Information about the customer.
 */
export class CreateOrderBodyOrderCustomer extends SpeakeasyBase {
    /**
     * The email of the customer associated with the order.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "email" })
    email: string;

    /**
     * The first name of the customer associated with the order.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "first_name" })
    firstName?: string;

    /**
     * The last name of the customer associated with the order.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "last_name" })
    lastName?: string;
}

export class CreateOrderBodyOrderLineItems extends SpeakeasyBase {
    /**
     * The quantity of the variant.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "quantity" })
    quantity: number;

    /**
     * The variant id associated with the line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "variant_id" })
    variantId: string;
}

/**
 * The shipping address of the order.
 */
export class CreateOrderBodyOrderShippingAddress extends SpeakeasyBase {
    /**
     * The first address line of the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "address1" })
    address1: string;

    /**
     * An optional second address line of the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "address2" })
    address2: string;

    /**
     * The city, town, or village of the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "city" })
    city: string;

    /**
     * The [ISO 3166-1](https://www.iso.org/iso-3166-country-codes.html) country code for the country of the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "country_code" })
    countryCode: string;

    /**
     * The email for the customer at the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "email" })
    email: string;

    /**
     * The first name of the person associated with the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "first_name" })
    firstName: string;

    /**
     * The last name of the person associated with the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "last_name" })
    lastName: string;

    /**
     * The phone number at the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "phone" })
    phone: string;

    /**
     * The postal code (ZIP, Eircode, etc) of the address.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "postal_code" })
    postalCode: string;

    /**
     * The abbreviation of the region of the address. For the US, this would be states, for other places, it would be provinces or equivalent.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "region" })
    region: string;
}

/**
 * The order to create.
 */
export class CreateOrderBodyOrder extends SpeakeasyBase {
    /**
     * The billing address of the order.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "billing_address" })
    @Type(() => CreateOrderBodyOrderBillingAddress)
    billingAddress: CreateOrderBodyOrderBillingAddress;

    /**
     * The [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html) currency code for the line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "currency_code" })
    currencyCode: string;

    /**
     * Information about the customer.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "customer" })
    @Type(() => CreateOrderBodyOrderCustomer)
    customer: CreateOrderBodyOrderCustomer;

    /**
     * An array of product variants included in the order and their quantities.
     */
    @SpeakeasyMetadata({ elemType: CreateOrderBodyOrderLineItems })
    @Expose({ name: "line_items" })
    @Type(() => CreateOrderBodyOrderLineItems)
    lineItems: CreateOrderBodyOrderLineItems[];

    /**
     * The shipping address of the order.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "shipping_address" })
    @Type(() => CreateOrderBodyOrderShippingAddress)
    shippingAddress?: CreateOrderBodyOrderShippingAddress;
}

export class CreateOrderBody extends SpeakeasyBase {
    /**
     * The order to create.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "order" })
    @Type(() => CreateOrderBodyOrder)
    order: CreateOrderBodyOrder;
}
