/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CreateInvoicePayment } from "./createinvoicepayment";
import { Expose, Type } from "class-transformer";

export class CreateCreateInvoicePaymentRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "invoice_payment" })
    @Type(() => CreateInvoicePayment)
    invoicePayment: CreateInvoicePayment;
}
