/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * The account type of the account.
 */
export enum CreateAccountAccountType {
    AccountsPayable = "accounts_payable",
    AccountsReceivable = "accounts_receivable",
    Bank = "bank",
    FixedAsset = "fixed_asset",
    OtherAsset = "other_asset",
    OtherCurrentAsset = "other_current_asset",
    Liability = "liability",
    Equity = "equity",
    Expense = "expense",
    OtherExpense = "other_expense",
    Income = "income",
    OtherIncome = "other_income",
    CreditCard = "credit_card",
    CostOfGoodsSold = "cost_of_goods_sold",
    OtherCurrentLiability = "other_current_liability",
    LongTermLiability = "long_term_liability",
    NonPosting = "non_posting",
    Unknown = "unknown",
}

/**
 * Additional fields required only for a narrow set of use cases.
 */
export class CreateAccountAdditionalFields extends SpeakeasyBase {
    /**
     * Xero only: required to create bank accounts.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "bank_account_number" })
    bankAccountNumber?: string;
}

/**
 * The [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html) currency code of the account.
 */
export enum CreateAccountCurrencyCode {
    Aed = "AED",
    Afn = "AFN",
    All = "ALL",
    Amd = "AMD",
    Ang = "ANG",
    Aoa = "AOA",
    Ars = "ARS",
    Aud = "AUD",
    Awg = "AWG",
    Azn = "AZN",
    Bam = "BAM",
    Bbd = "BBD",
    Bdt = "BDT",
    Bgn = "BGN",
    Bhd = "BHD",
    Bif = "BIF",
    Bmd = "BMD",
    Bnd = "BND",
    Bob = "BOB",
    Bov = "BOV",
    Brl = "BRL",
    Bsd = "BSD",
    Btn = "BTN",
    Bwp = "BWP",
    Byr = "BYR",
    Bzd = "BZD",
    Cad = "CAD",
    Cdf = "CDF",
    Che = "CHE",
    Chf = "CHF",
    Chw = "CHW",
    Clf = "CLF",
    Clp = "CLP",
    Cny = "CNY",
    Cop = "COP",
    Cou = "COU",
    Crc = "CRC",
    Cuc = "CUC",
    Cup = "CUP",
    Cve = "CVE",
    Czk = "CZK",
    Djf = "DJF",
    Dkk = "DKK",
    Dop = "DOP",
    Dzd = "DZD",
    Egp = "EGP",
    Ern = "ERN",
    Etb = "ETB",
    Eur = "EUR",
    Fjd = "FJD",
    Fkp = "FKP",
    Gbp = "GBP",
    Gel = "GEL",
    Ghs = "GHS",
    Gip = "GIP",
    Gmd = "GMD",
    Gnf = "GNF",
    Gtq = "GTQ",
    Gyd = "GYD",
    Hkd = "HKD",
    Hnl = "HNL",
    Hrk = "HRK",
    Htg = "HTG",
    Huf = "HUF",
    Idr = "IDR",
    Ils = "ILS",
    Inr = "INR",
    Iqd = "IQD",
    Irr = "IRR",
    Isk = "ISK",
    Jmd = "JMD",
    Jod = "JOD",
    Jpy = "JPY",
    Kes = "KES",
    Kgs = "KGS",
    Khr = "KHR",
    Kmf = "KMF",
    Kpw = "KPW",
    Krw = "KRW",
    Kwd = "KWD",
    Kyd = "KYD",
    Kzt = "KZT",
    Lak = "LAK",
    Lbp = "LBP",
    Lkr = "LKR",
    Lrd = "LRD",
    Lsl = "LSL",
    Ltl = "LTL",
    Lvl = "LVL",
    Lyd = "LYD",
    Mad = "MAD",
    Mdl = "MDL",
    Mga = "MGA",
    Mkd = "MKD",
    Mmk = "MMK",
    Mnt = "MNT",
    Mop = "MOP",
    Mro = "MRO",
    Mur = "MUR",
    Mvr = "MVR",
    Mwk = "MWK",
    Mxn = "MXN",
    Mxv = "MXV",
    Myr = "MYR",
    Mzn = "MZN",
    Nad = "NAD",
    Ngn = "NGN",
    Nio = "NIO",
    Nok = "NOK",
    Npr = "NPR",
    Nzd = "NZD",
    Omr = "OMR",
    Pab = "PAB",
    Pen = "PEN",
    Pgk = "PGK",
    Php = "PHP",
    Pkr = "PKR",
    Pln = "PLN",
    Pyg = "PYG",
    Qar = "QAR",
    Ron = "RON",
    Rsd = "RSD",
    Rub = "RUB",
    Rwf = "RWF",
    Sar = "SAR",
    Sbd = "SBD",
    Scr = "SCR",
    Sdg = "SDG",
    Sek = "SEK",
    Sgd = "SGD",
    Shp = "SHP",
    Sll = "SLL",
    Sos = "SOS",
    Srd = "SRD",
    Ssp = "SSP",
    Std = "STD",
    Syp = "SYP",
    Szl = "SZL",
    Thb = "THB",
    Tjs = "TJS",
    Tmt = "TMT",
    Tnd = "TND",
    Top = "TOP",
    Try = "TRY",
    Ttd = "TTD",
    Twd = "TWD",
    Tzs = "TZS",
    Uah = "UAH",
    Ugx = "UGX",
    Usd = "USD",
    Usn = "USN",
    Uss = "USS",
    Uyi = "UYI",
    Uyu = "UYU",
    Uzs = "UZS",
    Vef = "VEF",
    Vnd = "VND",
    Vuv = "VUV",
    Wst = "WST",
    Xaf = "XAF",
    Xag = "XAG",
    Xau = "XAU",
    Xba = "XBA",
    Xbb = "XBB",
    Xbc = "XBC",
    Xbd = "XBD",
    Xcd = "XCD",
    Xdr = "XDR",
    Xfu = "XFU",
    Xof = "XOF",
    Xpd = "XPD",
    Xpf = "XPF",
    Xpt = "XPT",
    Xts = "XTS",
    Xxx = "XXX",
    Yer = "YER",
    Zar = "ZAR",
    Zmw = "ZMW",
}

export class CreateAccount extends SpeakeasyBase {
    /**
     * The account type of the account.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "account_type" })
    accountType: CreateAccountAccountType;

    /**
     * Additional fields required only for a narrow set of use cases.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "additional_fields" })
    @Type(() => CreateAccountAdditionalFields)
    additionalFields?: CreateAccountAdditionalFields;

    /**
     * The [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html) currency code of the account.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "currency_code" })
    currencyCode: CreateAccountCurrencyCode;

    /**
     * The business facing name of the account.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    /**
     * The nominal code of the account used to classify accounts by department or account type.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "nominal_code" })
    nominalCode: string;

    /**
     * The Rutter ID of the [Subsidiary](/rest/version/subsidiaries) linked to the account. This feature is currently only supported on NetSuite.
     *
     * @remarks
     *   If a subsidiary ID is specified, the provided subsidiary as well as all children subsidiaries will be included as valid for the account. If no subsidiary info is specified, all subsidiaries will be included as valid for the account. (Note: accounts of type bank and credit_card can only have a single valid subsidiary.)
     */
    @SpeakeasyMetadata()
    @Expose({ name: "subsidiary_id" })
    subsidiaryId?: string;
}
