/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CreateAccount } from "./createaccount";
import { Expose, Type } from "class-transformer";

export class CreateCreateAccountRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "account" })
    @Type(() => CreateAccount)
    account: CreateAccount;
}
