/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { UpdateInvoicePayment } from "./updateinvoicepayment";
import { Expose, Type } from "class-transformer";

export class CreateUpdateInvoicePaymentRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "invoice_payment" })
    @Type(() => UpdateInvoicePayment)
    invoicePayment: UpdateInvoicePayment;
}
