/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CreateInvoiceCreditApplication } from "./createinvoicecreditapplication";
import { Expose, Type } from "class-transformer";

export class CreateCreateInvoiceCreditApplicationRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "invoice_credit_application" })
    @Type(() => CreateInvoiceCreditApplication)
    invoiceCreditApplication: CreateInvoiceCreditApplication;
}
