/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * Additional fields required only for a narrow set of use cases.
 */
export class CreateOrderFulfillmentBodyFulfillmentAdditionalFields extends SpeakeasyBase {
    /**
     * (Shopify only) Whether the customer should be notified. If set to true, then an email will be sent when the fulfillment is created or updated.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "notify_customer" })
    notifyCustomer?: boolean;
}

export class CreateOrderFulfillmentBodyFulfillmentLineItems extends SpeakeasyBase {
    /**
     * The ID of the line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "line_item_id" })
    lineItemId: string;

    /**
     * The number of the variants sold for this line_item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "quantity" })
    quantity?: number;
}

export class CreateOrderFulfillmentBodyFulfillment extends SpeakeasyBase {
    /**
     * Additional fields required only for a narrow set of use cases.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "additional_fields" })
    @Type(() => CreateOrderFulfillmentBodyFulfillmentAdditionalFields)
    additionalFields?: CreateOrderFulfillmentBodyFulfillmentAdditionalFields;

    /**
     * Carrier company, ex "USPS", "Fedex", "UPS", "Canada Post", etc. Can be any string.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "carrier" })
    carrier: string;

    /**
     * The product variants and quantities associated as part of this fulfillment.
     */
    @SpeakeasyMetadata({ elemType: CreateOrderFulfillmentBodyFulfillmentLineItems })
    @Expose({ name: "line_items" })
    @Type(() => CreateOrderFulfillmentBodyFulfillmentLineItems)
    lineItems: CreateOrderFulfillmentBodyFulfillmentLineItems[];

    /**
     * (Shopify only) The Shopify location id.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "location_id" })
    locationId?: string;

    /**
     * Carrier shipping service, e.g. "Priority Mail", "2 Day Delivery", etc. Can be any string.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "service" })
    service?: string;

    /**
     * Tracking number associated with this parcel.
     *
     * @remarks
     *   Usually buyers can track tracking info using this number at carrier's website.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tracking_number" })
    trackingNumber: string;

    /**
     * The tracking URL string that buyers can click to look up tracking information.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tracking_url" })
    trackingUrl?: string;
}

export class CreateOrderFulfillmentBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "fulfillment" })
    @Type(() => CreateOrderFulfillmentBodyFulfillment)
    fulfillment: CreateOrderFulfillmentBodyFulfillment;
}
