/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class CreateAttachmentBody extends SpeakeasyBase {
    /**
     * The file content (PDF, JPG, CSV, TXT, etc).
     */
    @SpeakeasyMetadata()
    @Expose({ name: "file" })
    file: string;

    /**
     * The file name of the attachment.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "file_name" })
    fileName: string;
}
