/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CreateSalesOrder } from "./createsalesorder";
import { Expose, Type } from "class-transformer";

export class CreateCreateSalesOrderRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "sales_order" })
    @Type(() => CreateSalesOrder)
    salesOrder: CreateSalesOrder;
}
