/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class CreateAccountingCustomer extends SpeakeasyBase {
    /**
     * The name of the contact person for the customer.  This will frequently be the name of the person who owns the contract.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "contact_name" })
    contactName: string;

    /**
     * The name of the customer. This will frequently be the company name.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "customer_name" })
    customerName: string;

    /**
     * The email address of the customer contact.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "email" })
    email: string;

    /**
     * The phone number of the customer contact.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "phone" })
    phone: string;

    /**
     * The Rutter ID of the [Subsidiary](/rest/version/subsidiaries) linked to the customer. This feature is currently only supported on NetSuite.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "subsidiary_id" })
    subsidiaryId?: string;
}
