/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class CreateProductBodyProductImages extends SpeakeasyBase {
    /**
     * The URL of the image.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "src" })
    src: string;
}

/**
 * The status of the product.
 */
export enum CreateProductBodyProductStatus {
    Active = "active",
    Archived = "archived",
    Inactive = "inactive",
    Draft = "draft",
    Unknown = "unknown",
}

export class CreateProductBodyProductVariantsImages extends SpeakeasyBase {
    /**
     * The URL of the image.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "src" })
    src: string;
}

export class CreateProductBodyProductVariantsInventory extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "location_id" })
    locationId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "total_count" })
    totalCount?: number;
}

export class CreateProductBodyProductVariantsOptionValues extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    @SpeakeasyMetadata()
    @Expose({ name: "value" })
    value: string;
}

export enum CreateProductBodyProductVariantsWeightUnit {
    Kg = "kg",
    G = "g",
    Oz = "oz",
    Lb = "lb",
    Gal = "gal",
}

export class CreateProductBodyProductVariantsWeight extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "unit" })
    unit: CreateProductBodyProductVariantsWeightUnit;

    @SpeakeasyMetadata()
    @Expose({ name: "value" })
    value: number;
}

export class CreateProductBodyProductVariants extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    @SpeakeasyMetadata({ elemType: CreateProductBodyProductVariantsImages })
    @Expose({ name: "images" })
    @Type(() => CreateProductBodyProductVariantsImages)
    images?: CreateProductBodyProductVariantsImages[];

    @SpeakeasyMetadata()
    @Expose({ name: "inventory" })
    @Type(() => CreateProductBodyProductVariantsInventory)
    inventory?: CreateProductBodyProductVariantsInventory;

    @SpeakeasyMetadata({ elemType: CreateProductBodyProductVariantsOptionValues })
    @Expose({ name: "option_values" })
    @Type(() => CreateProductBodyProductVariantsOptionValues)
    optionValues: CreateProductBodyProductVariantsOptionValues[];

    @SpeakeasyMetadata()
    @Expose({ name: "price" })
    price: number;

    @SpeakeasyMetadata()
    @Expose({ name: "sku" })
    sku: string;

    @SpeakeasyMetadata()
    @Expose({ name: "weight" })
    @Type(() => CreateProductBodyProductVariantsWeight)
    weight?: CreateProductBodyProductVariantsWeight;
}

export class CreateProductBodyProduct extends SpeakeasyBase {
    /**
     * The Rutter ID of the [category](/rest/version/category) linked to the product.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "category_id" })
    categoryId?: number;

    /**
     * The name of the product.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description: string;

    /**
     * An array of images linked to the product.
     */
    @SpeakeasyMetadata({ elemType: CreateProductBodyProductImages })
    @Expose({ name: "images" })
    @Type(() => CreateProductBodyProductImages)
    images?: CreateProductBodyProductImages[];

    /**
     * The name of the product.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    /**
     * The status of the product.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: CreateProductBodyProductStatus;

    /**
     * An array of tags linked to the product.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tags" })
    tags?: string[];

    /**
     * An array of [Variants](/rest/version/variants) linked to the product.
     */
    @SpeakeasyMetadata({ elemType: CreateProductBodyProductVariants })
    @Expose({ name: "variants" })
    @Type(() => CreateProductBodyProductVariants)
    variants: CreateProductBodyProductVariants[];
}

export class CreateProductBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "product" })
    @Type(() => CreateProductBodyProduct)
    product: CreateProductBodyProduct;
}
