/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CreateItem } from "./createitem";
import { Expose, Type } from "class-transformer";

export class CreateCreateItemRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "item" })
    @Type(() => CreateItem)
    item: CreateItem;
}
