/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class CreatePurchaseOrderLineItems extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "item" })
    item: string;

    /**
     * The quantity of the purchase order line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "quantity" })
    quantity: number;

    /**
     * The Rutter ID of the [Tax Rate](/rest/version/tax-rates) linked to the purchase order line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tax_rate_id" })
    taxRateId?: string;

    /**
     * The price per unit of the purchase order line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "unit_amount" })
    unitAmount?: number;
}

export class CreatePurchaseOrder extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "currency" })
    currency: string;

    @SpeakeasyMetadata()
    @Expose({ name: "currency_rate" })
    currencyRate?: number;

    @SpeakeasyMetadata({ elemType: CreatePurchaseOrderLineItems })
    @Expose({ name: "line_items" })
    @Type(() => CreatePurchaseOrderLineItems)
    lineItems: CreatePurchaseOrderLineItems[];

    @SpeakeasyMetadata()
    @Expose({ name: "memo" })
    memo?: string;

    /**
     * The Rutter ID of the [Subsidiary](/rest/version/subsidiaries) linked to the purchase order. This feature is currently only supported on NetSuite.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "subsidiary_id" })
    subsidiaryId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "txn_date" })
    txnDate?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "vendor_id" })
    vendorId: string;
}
