/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class CustomerOrders extends SpeakeasyBase {
    /**
     * The Rutter generated unique ID of the order.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;
}

export class Customer extends SpeakeasyBase {
    /**
     * The [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) timestamp that the customer was created.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "created_at" })
    createdAt: string;

    /**
     * The email of the customer.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "email" })
    email: string;

    /**
     * The first name of the customer.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "first_name" })
    firstName: string;

    /**
     * The Rutter generated unique ID of the customer.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    /**
     * The last name of the customer.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "last_name" })
    lastName: string;

    /**
     * An array of Rutter IDs of [Orders](/rest/version/orders) linked to the customer.
     */
    @SpeakeasyMetadata({ elemType: CustomerOrders })
    @Expose({ name: "orders" })
    @Type(() => CustomerOrders)
    orders: CustomerOrders[];

    /**
     * The phone number of the customer.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "phone" })
    phone: string;

    /**
     * The raw platform data corresponding to the Rutter object.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "platform_data" })
    platformData?: Record<string, any>;

    /**
     * The platform specific ID of the customer.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "platform_id" })
    platformId?: string;

    /**
     * The [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) timestamp that the customer was last updated.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "updated_at" })
    updatedAt: string;
}
