/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The status of the department.
 */
export enum DepartmentStatus {
    Active = "active",
    Archived = "archived",
}

export class Department extends SpeakeasyBase {
    /**
     * The [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) timestamp that the department was created.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "created_at" })
    createdAt: string;

    /**
     * Describes whether the department has child departments.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "has_children" })
    hasChildren: boolean;

    /**
     * The Rutter generated unique ID of the department.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    /**
     * The name of the department.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    /**
     * The Rutter ID of the [Parent Department](/rest/version/departments) linked to the department.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "parent_id" })
    parentId: string;

    /**
     * The raw platform data corresponding to the Rutter object.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "platform_data" })
    platformData?: Record<string, any>;

    /**
     * The platform specific ID of the department.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "platform_id" })
    platformId: string;

    /**
     * The status of the department.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: DepartmentStatus;

    /**
     * The [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) timestamp that the department was last updated.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "updated_at" })
    updatedAt: string;
}
