/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The entity type of the attachment.
 */
export enum EntityType {
    Bills = "bills",
    Expenses = "expenses",
    Invoices = "invoices",
    JournalEntries = "journal_entries",
}
