/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class ExchangeTokenBody extends SpeakeasyBase {
    /**
     * Your Rutter API `client_id`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "client_id" })
    clientId: string;

    /**
     * The `public_token` obtained from the Rutter Link `onSuccess` callback.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "public_token" })
    publicToken: string;

    /**
     * Your Rutter API `secret`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "secret" })
    secret: string;
}
