/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Optionally, include transaction information when fetching orders.
 */
export enum Expand1 {
    Transactions = "transactions",
}
