/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expense } from "./expense";
import { Expose, Type } from "class-transformer";

export class ExpenseResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "expense" })
    @Type(() => Expense)
    expense: Expense;
}
