/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CreateConnectionPlatforms } from "./createconnectionplatforms";
import { Expose } from "class-transformer";

/**
 * Credentials for Fnac
 */
export class FnacCredentials extends SpeakeasyBase {
    /**
     * Key
     */
    @SpeakeasyMetadata()
    @Expose({ name: "key" })
    key: string;

    /**
     * Partner ID
     */
    @SpeakeasyMetadata()
    @Expose({ name: "partner_id" })
    partnerId: string;

    /**
     * The underlying platform.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "platform" })
    platform: CreateConnectionPlatforms;

    @SpeakeasyMetadata()
    @Expose({ name: "scope" })
    scope?: string;

    /**
     * Shop ID
     */
    @SpeakeasyMetadata()
    @Expose({ name: "shop_id" })
    shopId: string;
}
