/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Force a response even if the underlying connection hasn't finished the initial sync.
 */
export enum ForceFetch {
    True = "true",
    False = "false",
}
