/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Optionally filter orders by their `fulfillment_status`.
 */
export enum FulfillmentStatus {
    Fulfilled = "fulfilled",
    Unfulfilled = "unfulfilled",
    Partial = "partial",
    Unknown = "unknown",
}
