/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Connection } from "./connection";
import { Store } from "./store";
import { Expose, Type } from "class-transformer";

export class GetStoreResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "connection" })
    @Type(() => Connection)
    connection?: Connection;

    @SpeakeasyMetadata()
    @Expose({ name: "store" })
    @Type(() => Store)
    store: Store;
}
