/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { GeneralLedgerLineItem } from "./generalledgerlineitem";
import { Expose, Type } from "class-transformer";

/**
 * The accounting standard used to generate the income statement.
 */
export enum IncomeStatementAccountingStandard {
    Cash = "cash",
    Accrual = "accrual",
    Unknown = "unknown",
}

export class IncomeStatement extends SpeakeasyBase {
    /**
     * The accounting standard used to generate the income statement.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "accounting_standard" })
    accountingStandard: IncomeStatementAccountingStandard;

    @SpeakeasyMetadata()
    @Expose({ name: "cost_of_sales" })
    @Type(() => GeneralLedgerLineItem)
    costOfSales: GeneralLedgerLineItem;

    /**
     * The [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) timestamp that the income statement was created.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "created_at" })
    createdAt: string;

    /**
     * The [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html) currency code of the income statement.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "currency_code" })
    currencyCode: string;

    /**
     * The [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) timestamp for the end date of the income statement accounting period.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "end_date" })
    endDate: string;

    @SpeakeasyMetadata()
    @Expose({ name: "expenses" })
    @Type(() => GeneralLedgerLineItem)
    expenses: GeneralLedgerLineItem;

    /**
     * Total profit after deducting the cost of sales.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "gross_profit" })
    grossProfit: string;

    /**
     * The Rutter generated unique ID of the income statement.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    @SpeakeasyMetadata()
    @Expose({ name: "income" })
    @Type(() => GeneralLedgerLineItem)
    income: GeneralLedgerLineItem;

    /**
     * Total Net Income in the given period.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "net_income" })
    netIncome: string;

    /**
     * Total Net Operating Income in the given period.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "net_operating_income" })
    netOperatingIncome?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "net_profit" })
    netProfit?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "net_sales" })
    netSales?: string;

    /**
     * The raw platform data corresponding to the Rutter object.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "platform_data" })
    platformData?: Record<string, any>;

    /**
     * The [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) timestamp for the start date of the income statement accounting period.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "start_date" })
    startDate: string;

    /**
     * The total cost of sales in the given period.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "total_cost_of_sales" })
    totalCostOfSales: string;

    /**
     * The total expense in the given period.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "total_expenses" })
    totalExpenses: string;

    /**
     * The total income in the given period.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "total_income" })
    totalIncome: string;

    /**
     * The [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) timestamp that the income statement was last updated.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "updated_at" })
    updatedAt: string;
}
