/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { InvoiceCreditApplication } from "./invoicecreditapplication";
import { Expose, Type } from "class-transformer";

export class InvoiceCreditApplicationResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "invoice_credit_application" })
    @Type(() => InvoiceCreditApplication)
    invoiceCreditApplication: InvoiceCreditApplication;
}
