/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class InvoiceCreditMemo20230207LineItems extends SpeakeasyBase {
    /**
     * The account being credited for the invoice line item
     */
    @SpeakeasyMetadata()
    @Expose({ name: "account_id" })
    accountId: string;

    /**
     * The total amount of the sales order line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "amount" })
    amount: string;

    /**
     * The description or memo of the invoice line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description: string;

    /**
     * The discount amount applied to the invoice line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "discount_amount" })
    discountAmount: string;

    /**
     * The percentage discount applied to the invoice line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "discount_percentage" })
    discountPercentage: string;

    /**
     * The Rutter generated unique ID of the invoice line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    /**
     * The Rutter ID of the [Item](/rest/version/items) linked to the invoice line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "item_id" })
    itemId: string;

    /**
     * The platform specific ID of the invoice line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "platform_id" })
    platformId: string;

    /**
     * The quantity of the invoice line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "quantity" })
    quantity: number;

    /**
     * The subtotal of the invoice line item, without tax.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "sub_total" })
    subTotal: string;

    /**
     * The total tax amount applied to the invoice line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tax_amount" })
    taxAmount: string;

    /**
     * The Rutter ID of the [Tax Rate](/rest/version/tax-rates) linked to the invoice line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tax_rate_id" })
    taxRateId: string;

    /**
     * The price per unit of the invoice line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "unit_amount" })
    unitAmount: string;
}

export class InvoiceCreditMemo20230207LinkedInvoices extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "allocated_amount" })
    allocatedAmount: string;

    @SpeakeasyMetadata()
    @Expose({ name: "allocated_date" })
    allocatedDate?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;
}

/**
 * The status of the invoice credit memo.
 */
export enum InvoiceCreditMemo20230207Status {
    Open = "OPEN",
    Applied = "APPLIED",
    PartiallyApplied = "PARTIALLY_APPLIED",
    Draft = "DRAFT",
    Unknown = "UNKNOWN",
}

export class InvoiceCreditMemo20230207 extends SpeakeasyBase {
    /**
     * The Rutter ID of the [Account](/rest/version/accounts) linked to the invoice. Represents the account being debited.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "account_id" })
    accountId: string;

    /**
     * The [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) timestamp for when the invoice credit memo was allocated.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "allocated_at" })
    allocatedAt: string;

    /**
     * The [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) timestamp that the invoice credit memo was created.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "created_at" })
    createdAt: string;

    /**
     * The [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html) currency code of the invoice credit memo.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "currency_code" })
    currencyCode: string;

    /**
     * The Rutter ID of the [Customer](/rest/version/accounting-customers) linked to the invoice credit memo.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "customer_id" })
    customerId: string;

    /**
     * The buyer facing document number of the invoice credit memo.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "document_number" })
    documentNumber: string;

    /**
     * The Rutter generated unique ID of the invoice credit memo.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    /**
     * The [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) timestamp for when the invoice credit memo was issued.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "issue_date" })
    issueDate: string;

    /**
     * An array of line items containing details about the invoice credit memo.
     */
    @SpeakeasyMetadata({ elemType: InvoiceCreditMemo20230207LineItems })
    @Expose({ name: "line_items" })
    @Type(() => InvoiceCreditMemo20230207LineItems)
    lineItems: InvoiceCreditMemo20230207LineItems[];

    /**
     * An array of Rutter IDs of [Invoices](/rest/version/invoices) linked to the invoice credit memo.
     */
    @SpeakeasyMetadata({ elemType: InvoiceCreditMemo20230207LinkedInvoices })
    @Expose({ name: "linked_invoices" })
    @Type(() => InvoiceCreditMemo20230207LinkedInvoices)
    linkedInvoices: InvoiceCreditMemo20230207LinkedInvoices[];

    /**
     * The memo of the invoice credit memo.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "memo" })
    memo: string;

    /**
     * The raw platform data corresponding to the Rutter object.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "platform_data" })
    platformData?: Record<string, any>;

    /**
     * The platform specific ID of the invoice credit memo.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "platform_id" })
    platformId: string;

    /**
     * The remaining unapplied amount of the invoice credit memo.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "remaining_amount" })
    remainingAmount: string;

    /**
     * The status of the invoice credit memo.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status: InvoiceCreditMemo20230207Status;

    /**
     * The total amount on the invoice credit memo.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "total_amount" })
    totalAmount: string;

    /**
     * The [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) timestamp that the invoice credit memo was last updated.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "updated_at" })
    updatedAt: string;
}
