/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { InvoiceCreditMemo } from "./invoicecreditmemo";
import { Expose, Type } from "class-transformer";

export class InvoiceCreditMemoResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "invoice_credit_memo" })
    @Type(() => InvoiceCreditMemo)
    invoiceCreditMemo: InvoiceCreditMemo;
}
