/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CreateConnectionPlatforms } from "./createconnectionplatforms";
import { Expose } from "class-transformer";

/**
 * Credentials for Lazada
 */
export class LazadaCredentials extends SpeakeasyBase {
    /**
     * Country Code for Merchant (e.g. id, sg, th)
     */
    @SpeakeasyMetadata()
    @Expose({ name: "country" })
    country: string;

    /**
     * OAuth Access Token
     */
    @SpeakeasyMetadata()
    @Expose({ name: "oauth_access_token" })
    oauthAccessToken: string;

    /**
     * OAuth Client ID
     */
    @SpeakeasyMetadata()
    @Expose({ name: "oauth_client_id" })
    oauthClientId: string;

    /**
     * OAuth Client Secret
     */
    @SpeakeasyMetadata()
    @Expose({ name: "oauth_client_secret" })
    oauthClientSecret: string;

    /**
     * OAuth Refresh Token
     */
    @SpeakeasyMetadata()
    @Expose({ name: "oauth_refresh_token" })
    oauthRefreshToken: string;

    /**
     * The underlying platform.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "platform" })
    platform: CreateConnectionPlatforms;

    @SpeakeasyMetadata()
    @Expose({ name: "scope" })
    scope?: string;
}
