/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class ListConnectionsResponseConnections extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "access_token" })
    accessToken: string;

    @SpeakeasyMetadata()
    @Expose({ name: "created_at" })
    createdAt: string;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    @SpeakeasyMetadata()
    @Expose({ name: "link_url" })
    linkUrl: string;

    @SpeakeasyMetadata()
    @Expose({ name: "platform" })
    platform: string;

    @SpeakeasyMetadata()
    @Expose({ name: "updated_at" })
    updatedAt: string;
}

export class ListConnectionsResponse extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: ListConnectionsResponseConnections })
    @Expose({ name: "connections" })
    @Type(() => ListConnectionsResponseConnections)
    connections: ListConnectionsResponseConnections[];
}
