/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Connection } from "./connection";
import { OrderTransaction } from "./ordertransaction";
import { Expose, Type } from "class-transformer";

export class ListTransactionsResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "connection" })
    @Type(() => Connection)
    connection: Connection;

    @SpeakeasyMetadata()
    @Expose({ name: "next_cursor" })
    nextCursor: string;

    @SpeakeasyMetadata({ elemType: OrderTransaction })
    @Expose({ name: "transactions" })
    @Type(() => OrderTransaction)
    transactions: OrderTransaction[];
}
