/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { BillPayment } from "./billpayment";
import { Connection } from "./connection";
import { Expose, Type } from "class-transformer";

export class ListBillPaymentResponseWithConnection extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: BillPayment })
    @Expose({ name: "bill_payments" })
    @Type(() => BillPayment)
    billPayments: BillPayment[];

    @SpeakeasyMetadata()
    @Expose({ name: "connection" })
    @Type(() => Connection)
    connection: Connection;

    @SpeakeasyMetadata()
    @Expose({ name: "next_cursor" })
    nextCursor?: string;
}
