/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Account } from "./account";
import { Connection } from "./connection";
import { Expose, Type } from "class-transformer";

export class ListAccountResponseWithConnection extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: Account })
    @Expose({ name: "accounts" })
    @Type(() => Account)
    accounts: Account[];

    @SpeakeasyMetadata()
    @Expose({ name: "connection" })
    @Type(() => Connection)
    connection: Connection;

    @SpeakeasyMetadata()
    @Expose({ name: "next_cursor" })
    nextCursor?: string;
}
