/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Connection } from "./connection";
import { SalesOrder20230314 } from "./salesorder20230314";
import { Expose, Type } from "class-transformer";

export class ListSalesOrder20230314ResponseWithConnection extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "connection" })
    @Type(() => Connection)
    connection: Connection;

    @SpeakeasyMetadata()
    @Expose({ name: "next_cursor" })
    nextCursor?: string;

    @SpeakeasyMetadata({ elemType: SalesOrder20230314 })
    @Expose({ name: "sales_orders" })
    @Type(() => SalesOrder20230314)
    salesOrders: SalesOrder20230314[];
}
