/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AccountingItem } from "./accountingitem";
import { Expose, Type } from "class-transformer";

export class ListAccountingItemResponse extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: AccountingItem })
    @Expose({ name: "items" })
    @Type(() => AccountingItem)
    items: AccountingItem[];

    @SpeakeasyMetadata()
    @Expose({ name: "next_cursor" })
    nextCursor?: string;
}
