/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Connection } from "./connection";
import { CustomerGroup } from "./customergroup";
import { Expose, Type } from "class-transformer";

export class ListCustomerGroupsResponseWithConnection extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "connection" })
    @Type(() => Connection)
    connection: Connection;

    @SpeakeasyMetadata({ elemType: CustomerGroup })
    @Expose({ name: "customer_groups" })
    @Type(() => CustomerGroup)
    customerGroups: CustomerGroup[];

    @SpeakeasyMetadata()
    @Expose({ name: "next_cursor" })
    nextCursor: string;
}
