/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Connection } from "./connection";
import { Product } from "./product";
import { Expose, Type } from "class-transformer";

export class ListProductsResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "connection" })
    @Type(() => Connection)
    connection: Connection;

    @SpeakeasyMetadata()
    @Expose({ name: "next_cursor" })
    nextCursor: string;

    @SpeakeasyMetadata({ elemType: Product })
    @Expose({ name: "products" })
    @Type(() => Product)
    products: Product[];
}
