/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CashFlowStatement } from "./cashflowstatement";
import { Expose, Type } from "class-transformer";

export class ListCashFlowStatementResponse extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: CashFlowStatement })
    @Expose({ name: "cash_flows" })
    @Type(() => CashFlowStatement)
    cashFlows: CashFlowStatement[];

    @SpeakeasyMetadata()
    @Expose({ name: "next_cursor" })
    nextCursor?: string;
}
