/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AccountingCustomer20230207 } from "./accountingcustomer20230207";
import { Connection } from "./connection";
import { Expose, Type } from "class-transformer";

export class ListAccountingCustomer20230207ResponseWithConnection extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "connection" })
    @Type(() => Connection)
    connection: Connection;

    @SpeakeasyMetadata({ elemType: AccountingCustomer20230207 })
    @Expose({ name: "customers" })
    @Type(() => AccountingCustomer20230207)
    customers: AccountingCustomer20230207[];

    @SpeakeasyMetadata()
    @Expose({ name: "next_cursor" })
    nextCursor?: string;
}
