/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Bill } from "./bill";
import { Connection } from "./connection";
import { Expose, Type } from "class-transformer";

export class ListBillResponseWithConnection extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: Bill })
    @Expose({ name: "bills" })
    @Type(() => Bill)
    bills: Bill[];

    @SpeakeasyMetadata()
    @Expose({ name: "connection" })
    @Type(() => Connection)
    connection: Connection;

    @SpeakeasyMetadata()
    @Expose({ name: "next_cursor" })
    nextCursor?: string;
}
