/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Connection } from "./connection";
import { Order } from "./order";
import { Expose, Type } from "class-transformer";

/**
 * The `/orders` endpoint allows developers to receive user-authorized order data for a merchant's store.
 *
 * @remarks
 *   Due to the potentially large number of orders associated with a connection, results are paginated.
 */
export class ListOrdersResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "connection" })
    @Type(() => Connection)
    connection: Connection;

    @SpeakeasyMetadata()
    @Expose({ name: "next_cursor" })
    nextCursor: string;

    @SpeakeasyMetadata({ elemType: Order })
    @Expose({ name: "orders" })
    @Type(() => Order)
    orders: Order[];
}
