/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { BillCreditMemo } from "./billcreditmemo";
import { Connection } from "./connection";
import { Expose, Type } from "class-transformer";

export class ListBillCreditMemoResponseWithConnection extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: BillCreditMemo })
    @Expose({ name: "bill_credit_memos" })
    @Type(() => BillCreditMemo)
    billCreditMemos: BillCreditMemo[];

    @SpeakeasyMetadata()
    @Expose({ name: "connection" })
    @Type(() => Connection)
    connection: Connection;

    @SpeakeasyMetadata()
    @Expose({ name: "next_cursor" })
    nextCursor?: string;
}
