/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CreateConnectionPlatforms } from "./createconnectionplatforms";
import { Expose } from "class-transformer";

/**
 * Credentials for PrestaShop
 */
export class PrestaShopCredentials extends SpeakeasyBase {
    /**
     * PrestaShop API Key
     */
    @SpeakeasyMetadata()
    @Expose({ name: "api_key" })
    apiKey: string;

    /**
     * The underlying platform.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "platform" })
    platform: CreateConnectionPlatforms;

    @SpeakeasyMetadata()
    @Expose({ name: "scope" })
    scope?: string;

    /**
     * PrestaShop merchant domain URL
     */
    @SpeakeasyMetadata()
    @Expose({ name: "store_url" })
    storeUrl: string;
}
