/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class ProductCategory extends SpeakeasyBase {
    /**
     * Array of sub-categories in the same format.
     */
    @SpeakeasyMetadata({ elemType: ProductCategory })
    @Expose({ name: "children" })
    @Type(() => ProductCategory)
    children?: ProductCategory[];

    /**
     * The Rutter generated unique ID of the product category.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    /**
     * The name of the category
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;
}
