/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { PurchaseOrder } from "./purchaseorder";
import { Expose, Type } from "class-transformer";

export class PurchaseOrderResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "purchase_order" })
    @Type(() => PurchaseOrder)
    purchaseOrder: PurchaseOrder;
}
