/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CreateConnectionPlatforms } from "./createconnectionplatforms";
import { Expose } from "class-transformer";

/**
 * Credentials for Quickbooks
 */
export class QuickbooksCredentials extends SpeakeasyBase {
    /**
     * Environment (e.g. sandbox)
     */
    @SpeakeasyMetadata()
    @Expose({ name: "environment" })
    environment?: string;

    /**
     * OAuth Client ID
     */
    @SpeakeasyMetadata()
    @Expose({ name: "oauth_client_id" })
    oauthClientId: string;

    /**
     * OAuth Client Secret
     */
    @SpeakeasyMetadata()
    @Expose({ name: "oauth_client_secret" })
    oauthClientSecret: string;

    /**
     * OAuth Refresh Token
     */
    @SpeakeasyMetadata()
    @Expose({ name: "oauth_refresh_token" })
    oauthRefreshToken: string;

    /**
     * The underlying platform.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "platform" })
    platform: CreateConnectionPlatforms;

    /**
     * Realm ID
     */
    @SpeakeasyMetadata()
    @Expose({ name: "realm_id" })
    realmId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "scope" })
    scope?: string;
}
