/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Connection } from "./connection";
import { SalesOrder20230314 } from "./salesorder20230314";
import { Expose, Type } from "class-transformer";

export class SalesOrder20230314ResponseWithConnection extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "connection" })
    @Type(() => Connection)
    connection: Connection;

    @SpeakeasyMetadata()
    @Expose({ name: "sales_order" })
    @Type(() => SalesOrder20230314)
    salesOrder: SalesOrder20230314;
}
