/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CreateConnectionPlatforms } from "./createconnectionplatforms";
import { Expose } from "class-transformer";

/**
 * Credentials for Shopify Public App
 */
export class ShopifyPublicCredentials extends SpeakeasyBase {
    /**
     * Shopify Merchant Access Token
     */
    @SpeakeasyMetadata()
    @Expose({ name: "oauth_access_token" })
    oauthAccessToken: string;

    /**
     * Shopify Public App Client ID
     */
    @SpeakeasyMetadata()
    @Expose({ name: "oauth_client_id" })
    oauthClientId: string;

    /**
     * Shopify Public App Client Secret
     */
    @SpeakeasyMetadata()
    @Expose({ name: "oauth_client_secret" })
    oauthClientSecret: string;

    /**
     * The underlying platform.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "platform" })
    platform: CreateConnectionPlatforms;

    @SpeakeasyMetadata()
    @Expose({ name: "scope" })
    scope?: string;

    /**
     * Shopify merchant .myshopify.com domain URL
     */
    @SpeakeasyMetadata()
    @Expose({ name: "store_url" })
    storeUrl: string;
}
