/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CreateConnectionPlatforms } from "./createconnectionplatforms";
import { Expose } from "class-transformer";

/**
 * Credentials for Shopify Private App
 */
export class ShopifyPrivateCredentials extends SpeakeasyBase {
    /**
     * Private Shopify App Password
     */
    @SpeakeasyMetadata()
    @Expose({ name: "basic_password" })
    basicPassword: string;

    /**
     * Private Shopify App API Key
     */
    @SpeakeasyMetadata()
    @Expose({ name: "basic_username" })
    basicUsername: string;

    /**
     * The underlying platform.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "platform" })
    platform: CreateConnectionPlatforms;

    @SpeakeasyMetadata()
    @Expose({ name: "scope" })
    scope?: string;

    /**
     * Shopify merchant .myshopify.com domain URL
     */
    @SpeakeasyMetadata()
    @Expose({ name: "store_url" })
    storeUrl: string;
}
