/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CreateConnectionPlatforms } from "./createconnectionplatforms";
import { Expose } from "class-transformer";

/**
 * Credentials for Shoper
 */
export class ShoperCredentials extends SpeakeasyBase {
    /**
     * Shoper merchant OAuth Access Token
     */
    @SpeakeasyMetadata()
    @Expose({ name: "oauth_access_token" })
    oauthAccessToken: string;

    /**
     * Shoper merchant OAuth Refresh Token
     */
    @SpeakeasyMetadata()
    @Expose({ name: "oauth_refresh_token" })
    oauthRefreshToken: string;

    /**
     * The underlying platform.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "platform" })
    platform: CreateConnectionPlatforms;

    @SpeakeasyMetadata()
    @Expose({ name: "scope" })
    scope?: string;

    /**
     * Shoper merchant domain URL
     */
    @SpeakeasyMetadata()
    @Expose({ name: "store_url" })
    storeUrl: string;
}
