/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Show products with certain product status.
 */
export enum Status {
    Active = "active",
    Archived = "archived",
    Inactive = "inactive",
    Draft = "draft",
}
