/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class Store extends SpeakeasyBase {
    /**
     * The [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html) currency code of the store.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "default_currency" })
    defaultCurrency: string;

    /**
     * The email of the primary contact of the store.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "email" })
    email?: string;

    /**
     * The Rutter generated unique ID of the store.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    /**
     * The unique identifier or brand name of the store.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "store_name" })
    storeName: string;

    /**
     * The consumer facing URL of the store.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "url" })
    url: string;
}
