/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * The status of the product.
 */
export enum UpdateProductBodyProductStatus {
    Active = "active",
    Archived = "archived",
    Inactive = "inactive",
    Draft = "draft",
    Unknown = "unknown",
}

export class UpdateProductBodyProduct extends SpeakeasyBase {
    /**
     * The description of the product.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    /**
     * The name of the product.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * The status of the product.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: UpdateProductBodyProductStatus;
}

export class UpdateProductBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "product" })
    @Type(() => UpdateProductBodyProduct)
    product: UpdateProductBodyProduct;
}
