/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class UpdateInvoicePaymentLinkedInvoices extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "allocated_at" })
    allocatedAt?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "amount" })
    amount: number;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;
}

export class UpdateInvoicePayment extends SpeakeasyBase {
    /**
     * The Rutter ID of the [Account](/rest/version/accounts) linked to the invoice payment. This should be a bank account.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "account_id" })
    accountId?: string;

    /**
     * The Rutter ID of the [Customer](/rest/version/accounting-customers) linked to the invoice payment.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "customer_id" })
    customerId?: string;

    /**
     * An array of [Invoices](/rest/version/invoices) linked to the invoice payment.
     */
    @SpeakeasyMetadata({ elemType: UpdateInvoicePaymentLinkedInvoices })
    @Expose({ name: "linked_invoices" })
    @Type(() => UpdateInvoicePaymentLinkedInvoices)
    linkedInvoices?: UpdateInvoicePaymentLinkedInvoices[];

    /**
     * The memo of the invoice payment.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "memo" })
    memo?: string;

    /**
     * The total amount on the invoice payment.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "total_amount" })
    totalAmount?: number;

    /**
     * The [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) timestamp for when the transaction was logged.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "txn_date" })
    txnDate?: string;
}
