/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class UpdateBillBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "document_number" })
    documentNumber?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "due_date" })
    dueDate?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "issue_date" })
    issueDate?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "memo" })
    memo?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "vendor_id" })
    vendorId?: string;
}
