/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { UpdateBillResponse } from "./updatebillresponse";
import { Expose, Type } from "class-transformer";

export class UpdateBillResponseResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "bill" })
    @Type(() => UpdateBillResponse)
    bill: UpdateBillResponse;
}
