/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * The [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html) currency code of the bill.
 */
export enum UpdateBillResponseCurrencyCode {
    Aed = "AED",
    Afn = "AFN",
    All = "ALL",
    Amd = "AMD",
    Ang = "ANG",
    Aoa = "AOA",
    Ars = "ARS",
    Aud = "AUD",
    Awg = "AWG",
    Azn = "AZN",
    Bam = "BAM",
    Bbd = "BBD",
    Bdt = "BDT",
    Bgn = "BGN",
    Bhd = "BHD",
    Bif = "BIF",
    Bmd = "BMD",
    Bnd = "BND",
    Bob = "BOB",
    Bov = "BOV",
    Brl = "BRL",
    Bsd = "BSD",
    Btn = "BTN",
    Bwp = "BWP",
    Byr = "BYR",
    Bzd = "BZD",
    Cad = "CAD",
    Cdf = "CDF",
    Che = "CHE",
    Chf = "CHF",
    Chw = "CHW",
    Clf = "CLF",
    Clp = "CLP",
    Cny = "CNY",
    Cop = "COP",
    Cou = "COU",
    Crc = "CRC",
    Cuc = "CUC",
    Cup = "CUP",
    Cve = "CVE",
    Czk = "CZK",
    Djf = "DJF",
    Dkk = "DKK",
    Dop = "DOP",
    Dzd = "DZD",
    Egp = "EGP",
    Ern = "ERN",
    Etb = "ETB",
    Eur = "EUR",
    Fjd = "FJD",
    Fkp = "FKP",
    Gbp = "GBP",
    Gel = "GEL",
    Ghs = "GHS",
    Gip = "GIP",
    Gmd = "GMD",
    Gnf = "GNF",
    Gtq = "GTQ",
    Gyd = "GYD",
    Hkd = "HKD",
    Hnl = "HNL",
    Hrk = "HRK",
    Htg = "HTG",
    Huf = "HUF",
    Idr = "IDR",
    Ils = "ILS",
    Inr = "INR",
    Iqd = "IQD",
    Irr = "IRR",
    Isk = "ISK",
    Jmd = "JMD",
    Jod = "JOD",
    Jpy = "JPY",
    Kes = "KES",
    Kgs = "KGS",
    Khr = "KHR",
    Kmf = "KMF",
    Kpw = "KPW",
    Krw = "KRW",
    Kwd = "KWD",
    Kyd = "KYD",
    Kzt = "KZT",
    Lak = "LAK",
    Lbp = "LBP",
    Lkr = "LKR",
    Lrd = "LRD",
    Lsl = "LSL",
    Ltl = "LTL",
    Lvl = "LVL",
    Lyd = "LYD",
    Mad = "MAD",
    Mdl = "MDL",
    Mga = "MGA",
    Mkd = "MKD",
    Mmk = "MMK",
    Mnt = "MNT",
    Mop = "MOP",
    Mro = "MRO",
    Mur = "MUR",
    Mvr = "MVR",
    Mwk = "MWK",
    Mxn = "MXN",
    Mxv = "MXV",
    Myr = "MYR",
    Mzn = "MZN",
    Nad = "NAD",
    Ngn = "NGN",
    Nio = "NIO",
    Nok = "NOK",
    Npr = "NPR",
    Nzd = "NZD",
    Omr = "OMR",
    Pab = "PAB",
    Pen = "PEN",
    Pgk = "PGK",
    Php = "PHP",
    Pkr = "PKR",
    Pln = "PLN",
    Pyg = "PYG",
    Qar = "QAR",
    Ron = "RON",
    Rsd = "RSD",
    Rub = "RUB",
    Rwf = "RWF",
    Sar = "SAR",
    Sbd = "SBD",
    Scr = "SCR",
    Sdg = "SDG",
    Sek = "SEK",
    Sgd = "SGD",
    Shp = "SHP",
    Sll = "SLL",
    Sos = "SOS",
    Srd = "SRD",
    Ssp = "SSP",
    Std = "STD",
    Syp = "SYP",
    Szl = "SZL",
    Thb = "THB",
    Tjs = "TJS",
    Tmt = "TMT",
    Tnd = "TND",
    Top = "TOP",
    Try = "TRY",
    Ttd = "TTD",
    Twd = "TWD",
    Tzs = "TZS",
    Uah = "UAH",
    Ugx = "UGX",
    Usd = "USD",
    Usn = "USN",
    Uss = "USS",
    Uyi = "UYI",
    Uyu = "UYU",
    Uzs = "UZS",
    Vef = "VEF",
    Vnd = "VND",
    Vuv = "VUV",
    Wst = "WST",
    Xaf = "XAF",
    Xag = "XAG",
    Xau = "XAU",
    Xba = "XBA",
    Xbb = "XBB",
    Xbc = "XBC",
    Xbd = "XBD",
    Xcd = "XCD",
    Xdr = "XDR",
    Xfu = "XFU",
    Xof = "XOF",
    Xpd = "XPD",
    Xpf = "XPF",
    Xpt = "XPT",
    Xts = "XTS",
    Xxx = "XXX",
    Yer = "YER",
    Zar = "ZAR",
    Zmw = "ZMW",
}

/**
 * The product or service associated with the bill line item.
 */
export class UpdateBillResponseLineItemsItem extends SpeakeasyBase {
    /**
     * The Rutter ID of the [Item](/rest/version/items) linked to the bill line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    /**
     * The quantity of items in the bill line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "quantity" })
    quantity: number;

    /**
     * The unit amount of the items in the bill line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "unit_amount" })
    unitAmount: number;
}

export class UpdateBillResponseLineItems extends SpeakeasyBase {
    /**
     * The Rutter ID of the [Account](/rest/version/accounts) linked to the bill line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "account_id" })
    accountId: string;

    /**
     * The Rutter ID of the [Class](/rest/version/classes) linked to the bill line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "class_id" })
    classId: string;

    /**
     * The Rutter ID of the [Customer](/rest/version/customers) linked to the bill line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "customer_id" })
    customerId: string;

    /**
     * The Rutter ID of the [Department](/rest/version/departments) linked to the bill line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "department_id" })
    departmentId: string;

    /**
     * The description or memo of the bill line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description: string;

    /**
     * The discount amount applied to the bill line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "discount_amount" })
    discountAmount: number;

    /**
     * The percentage discount applied to the bill line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "discount_percentage" })
    discountPercentage: number;

    /**
     * The product or service associated with the bill line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "item" })
    @Type(() => UpdateBillResponseLineItemsItem)
    item: UpdateBillResponseLineItemsItem;

    /**
     * The Rutter ID of the [Location](/rest/version/locations) linked to the bill line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "location_id" })
    locationId: string;

    /**
     * The subtotal of the bill line item, without tax.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "sub_total" })
    subTotal: number;

    /**
     * The tax amount applied to the bill line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tax_amount" })
    taxAmount: number;

    /**
     * The Rutter ID of the [Tax Rate](/rest/version/tax-rates) linked to the bill line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tax_rate_id" })
    taxRateId: string;

    /**
     * The total amount of the bill line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "total_amount" })
    totalAmount: number;
}

export class UpdateBillResponseLinkedCreditMemos extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "allocated_amount" })
    allocatedAmount: number;

    @SpeakeasyMetadata()
    @Expose({ name: "allocated_date" })
    allocatedDate: string;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;
}

export class UpdateBillResponseLinkedPayments extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "allocated_amount" })
    allocatedAmount: number;

    @SpeakeasyMetadata()
    @Expose({ name: "allocated_date" })
    allocatedDate: string;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;
}

export class UpdateBillResponseLinkedPurchaseOrders extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;
}

/**
 * The status of the bill.
 */
export enum UpdateBillResponseStatus {
    Open = "open",
    PartiallyPaid = "partially_paid",
    Paid = "paid",
    Void = "void",
    Draft = "draft",
    Unknown = "unknown",
    Submitted = "submitted",
}

export class UpdateBillResponse extends SpeakeasyBase {
    /**
     * The Rutter ID of the [Account](/rest/version/accounts) linked to the bill. Represents the AP account being credited.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "account_id" })
    accountId: string;

    /**
     * The current amount due on the bill. Represents the remainder after bill payments or bill credit memos are applied against the total amount.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "amount_due" })
    amountDue: number;

    /**
     * The [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) timestamp that the bill was created.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "created_at" })
    createdAt: string;

    /**
     * The [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html) currency code of the bill.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "currency_code" })
    currencyCode: UpdateBillResponseCurrencyCode;

    /**
     * The buyer facing document number of the bill.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "document_number" })
    documentNumber: string;

    @SpeakeasyMetadata()
    @Expose({ name: "due_date" })
    dueDate: string;

    /**
     * The Rutter generated unique ID of the bill.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    /**
     * The [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) timestamp for the issue date of the bill.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "issue_date" })
    issueDate: string;

    /**
     * An array of line items associated with the bill.
     */
    @SpeakeasyMetadata({ elemType: UpdateBillResponseLineItems })
    @Expose({ name: "line_items" })
    @Type(() => UpdateBillResponseLineItems)
    lineItems: UpdateBillResponseLineItems[];

    /**
     * An array of Rutter IDs of [Bill Credit Memos](/reference/bill-credit-memos) applied against the bill.
     */
    @SpeakeasyMetadata({ elemType: UpdateBillResponseLinkedCreditMemos })
    @Expose({ name: "linked_credit_memos" })
    @Type(() => UpdateBillResponseLinkedCreditMemos)
    linkedCreditMemos: UpdateBillResponseLinkedCreditMemos[];

    /**
     * An array of Rutter IDs of [Bill Payments](/reference/bill-payments) applied against the bill.
     */
    @SpeakeasyMetadata({ elemType: UpdateBillResponseLinkedPayments })
    @Expose({ name: "linked_payments" })
    @Type(() => UpdateBillResponseLinkedPayments)
    linkedPayments: UpdateBillResponseLinkedPayments[];

    /**
     * An array of Rutter IDs of [Purchase Orders](/rest/version/purchase-orders) linked to the bill.
     */
    @SpeakeasyMetadata({ elemType: UpdateBillResponseLinkedPurchaseOrders })
    @Expose({ name: "linked_purchase_orders" })
    @Type(() => UpdateBillResponseLinkedPurchaseOrders)
    linkedPurchaseOrders: UpdateBillResponseLinkedPurchaseOrders[];

    /**
     * Memo or description of the bill
     */
    @SpeakeasyMetadata()
    @Expose({ name: "memo" })
    memo: string;

    /**
     * The raw platform data corresponding to the Rutter object.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "platform_data" })
    platformData?: Record<string, any>;

    /**
     * The platform specific ID of the bill.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "platform_id" })
    platformId: string;

    /**
     * The status of the bill.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status: UpdateBillResponseStatus;

    /**
     * The subtotal of the bill, without the tax amount.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "sub_total" })
    subTotal: number;

    /**
     * The Rutter ID of the [Subsidiary](/rest/version/subsidiaries) linked to the bill. This feature is currently only supported on NetSuite.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "subsidiary_id" })
    subsidiaryId: string;

    /**
     * The tax amount applied to the bill.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tax_amount" })
    taxAmount: number;

    /**
     * The total amount due on the bill.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "total_amount" })
    totalAmount: number;

    /**
     * The discount amount applied to the bill.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "total_discount" })
    totalDiscount: number;

    /**
     * The [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) timestamp that the bill was last updated.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "updated_at" })
    updatedAt: string;

    /**
     * The Rutter ID of the [Vendor](/rest/version/vendors) linked to the bill.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "vendor_id" })
    vendorId: string;
}
