/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Vendor } from "./vendor";
import { Expose, Type } from "class-transformer";

export class VendorResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "vendor" })
    @Type(() => Vendor)
    vendor: Vendor;
}
