/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CreateConnectionPlatforms } from "./createconnectionplatforms";
import { Expose } from "class-transformer";

/**
 * Credentials for Walmart
 */
export class WalmartCredentials extends SpeakeasyBase {
    /**
     * Walmart Developer OAuth Client ID
     */
    @SpeakeasyMetadata()
    @Expose({ name: "oauth_client_id" })
    oauthClientId: string;

    /**
     * Walmart Developer OAuth Client Secret
     */
    @SpeakeasyMetadata()
    @Expose({ name: "oauth_client_secret" })
    oauthClientSecret: string;

    /**
     * The underlying platform.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "platform" })
    platform: CreateConnectionPlatforms;

    @SpeakeasyMetadata()
    @Expose({ name: "scope" })
    scope?: string;
}
