/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class CreateProductRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    createProductBody: shared.CreateProductBody;

    /**
     * The access token of the connection.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=access_token" })
    accessToken: string;
}

export class CreateProduct200ApplicationJson2 extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "product" })
    @Type(() => shared.Product)
    product: shared.Product;
}

export class CreateProduct200ApplicationJson1 extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "job_id" })
    jobId: string;
}

export class CreateProductResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    createProductResponse?: any;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
